language: python
services:
  - redis-server
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - pytest --cov celery_once --cov-report term-missing
  - celery -A tests.integration.flask_app.app.celery worker&
  - sleep 5
  - pytest -m "framework"
after_success:
  - coveralls
